config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :downgrade
  get 'downgrades', to: 'downgrades#downgrade_account', as: 'downgrade_plan'
  post 'downgrades', to: 'downgrades#downgrade_account', as: 'standard_plan'

  devise_for :users, controllers: {sessions: 'users/sessions'}
  resources :wikis
  # resources :users
  get '/plans', to: 'welcome#plans'
  get '/about', to: 'welcome#about'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_action :configure_permitted_parameters
  # before_action :authenticate_user!
  # protect_from_forgery with: :exception
  #
  # protected
  #
  # def configure_permitted_parameters
  # devise_parameter_sanitizer.permit(:sign_in) do |user_params|
  #   user_params.permit(:name, :email, :wiki)
  #   end
  # end

  # def show
  # end
  #
  # def index
  # end
  #
  # def about
  # end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div id="content">
  <section class="hello" id="about">
    <div class="container">
      <div class="col-sm-6">
        <div class="heading-block">
          <h1 class="huge-tittle animate fadeInRight">about</h1>
          <h6 class="animate fadeInRight">Blocipedia</h6>
          <%= image_tag "_img/icon-services-2.png", class:"about-img animate fadeInLeft", alt:"blocipedia" %>
        </div>
      </div>

        <div class="col-sm-6">
          <div class="about-lead">
            <p class="lead">read, build, or collaborate on community-sourced content...
            <br>
            <br>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <div>
              <a href="#." class="btn-sm">Get Started</a>
            </div>
          </div>
        </div>
    </div>
  </section>
</div>

<hr class="featurette-divider">
<div class="content">
  <section class="bloc-plans" id="plans">
    <div class="container">
      <div class="row">
        <div class="col-lg heading-block">
          <h1 class="bloc-plans-heading huge-tittle">Select a Plan</h1>
        </div>
        <div class="col-sm-6 col-md-6">
          <div class="thumbnail">
            <%= image_tag "about-plan-placeholder1.png", class:"rounded-circle", alt:"Generic placeholder image" %>
            <div class="caption">
              <h2 class="plan">Standard</h2>
              <h3>Free</h3>
              <p>Sustainable Polaroid raw denim four loko vexillologist, hexagon viral whatever kitsch dreamcatcher umami art party. </p>
              <p><a href="#" class="btn-sm" role="button">Button</a></p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-6">
          <div class="thumbnail">
            <%= image_tag "about-plan-placeholder2.png", class:"rounded-circle", alt:"Generic placeholder image" %>
            <div class="caption">
              <h2 class="plan">Premium</h2>
              <h3>$9.99</h3>
              <p>DIY disrupt dreamcatcher, cornhole leggings pork belly meditation polaroid chia XOXO offal irony VHS shaman.</p>
              <p><a href="#" class="btn-sm" role="button">Button</a></p>
            </div>
          </div>
        </div>
      </div>

  </section>
</div>

app/views/welcome/index.html.erb
<!--g:HOME-->
<div class="home-agency">
  <div class="position-center-center">
    <div class="container">
      <div class="ag-text">
        <h3 class="animate fadeInDown" data-wow-delay="0.4s">Welcome to</h3>
        <h1 class="animate fadeInDown" data-wow-delay="0.6s">Blocipedia</h1>
        <p class="animate fadeInDown" data-wow-delay="0.8s">Knowledge Meets Collaboration</p>
      </div>
    </div>
  </div>
</div>

<%if user_signed_in?%>

  <div id="content">
    <!-- a:ABOUT SECTION-->
    <section class="hello" id="about">
      <!-- Diagonal Top -->
      <div class="cir-tri-bg"></div>
      <div class="container">

          <!-- Heading Block -->
          <div class="heading-block">
            <h6 class="animate fadeInRight" data-wow-delay="0.4s">What is Blocipedia?</h6>
            <span class="huge-tittle">about</span> </div>

          <div class="col-sm-5" data-wow-delay="0.5s">
            <%= image_tag "_img/icon-services-2.png", class:"hello-img animate fadeInLeft", alt:"blocipedia" %>
          </div>
          <!-- CONTENT INFO -->
          <div class="col-sm-7">
            <h4>Simply put, Blocipedia is a place for Knowledge & Collaboration.</h4>
            <div class="test-info">
              <p>read, build, or collaborate on community-sourced content...</p>
              <a href="#." class="btn-flat">Get Started</a> </div>
          </div>
      </div>
      <!-- Bottom BG Style -->
      <div class="cir-bottom-bg"></div>
    </section>
    <!-- b:WORK SECTION -->
    <section class="work-process" id="workflow-process">
        <!-- TOP bg Style -->
        <div class="cir-tri-bg" data-stellar-background-ratio="0.4"></div>
        <div class="container">

          <!-- Heading Block -->
          <div class="heading-block white">
            <h6 class="animate fadeInRight" data-wow-delay="0.4s">workflow</h6>
            <span class="huge-tittle">process</span> </div>

            <!-- Process Steps -->
            <div class="process-style-2">
              <ul class="row">
                <!-- write -->
                <li>
                  <div class="media-left">
                    <div class="icon animate fadeInLeft" data-wow-delay="0.4s">
                      <%= image_tag "_img/process-icon-1.png", class:"", alt:"blocipedia" %>
                      <!-- <img src="images/process-icon-1.png" alt="" >  -->
                    </div>
                  </div>
                  <div class="media-body">
                    <h4>Write</h4>
                    <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aes bib auctor.</p>
                  </div>
                </li>
                <!-- read -->
                <li>
                  <div class="media-left">
                    <div class="icon animate fadeInLeft" data-wow-delay="0.4s">
                      <%= image_tag "_img/process-icon-2.png", class:"", alt:"blocipedia" %>
                      <!-- <img src="images/process-icon-2.png" alt="" >  -->
                    </div>
                  </div>
                  <div class="media-body">
                    <h4>Read</h4>
                    <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aes bib auctor.</p>
                  </div>
                </li>
                <!-- Brainstorm -->
                <li>
                  <div class="media-left">
                    <div class="icon animate fadeInLeft" data-wow-delay="0.4s">
                      <%= image_tag "_img/process-icon-3.png", class:"", alt:"blocipedia" %>
                      <!-- <img src="images/process-icon-3.png" alt="" >  -->
                    </div>
                  </div>
                  <div class="media-body">
                    <h4>Brainstorm</h4>
                    <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aes bib auctor.</p>
                  </div>
                </li>
                <!-- create -->
                <li>
                  <div class="media-left">
                    <div class="icon animate fadeInLeft" data-wow-delay="0.4s">
                      <%= image_tag "_img/process-icon-4.png", class:"", alt:"blocipedia" %>
                      <!-- <img src="images/process-icon-4.png" alt="" >  -->
                    </div>
                  </div>
                  <div class="media-body">
                    <h4>create</h4>
                    <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aes bib auctor.</p>
                  </div>
                </li>
                <!-- Launch -->
                <li>
                  <div class="media-left">
                    <div class="icon animate fadeInLeft" data-wow-delay="0.4s">
                      <%= image_tag "_img/process-icon-5.png", class:"", alt:"blocipedia" %>
                      <!-- <img src="images/process-icon-5.png" alt="" >  -->
                    </div>
                  </div>
                  <div class="media-body">
                    <h4>Launch</h4>
                    <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aes bib auctor.</p>
                  </div>
                </li>
              </ul>
            </div>
        </div>
        <!-- <div class="cir-bottom-bg"></div> -->
    </section>
    <!-- c:PLANS SECTION -->
    <section class="profile-main" id="plans" data-stellar-background-ratio="0.5">
        <!-- TOP bg Style -->
        <div class="cir-bottom-bg"></div>
        <div class="container">

          <!-- Heading Block -->
          <div class="heading-block">
            <h6 class="animate fadeInRight" data-wow-delay="0.4s">sign up today</h6>
            <span class="huge-tittle">plans</span> </div>

          <!-- Plan Tabs -->
          <div class="profile-inn plan-table">
            <div class="row">
              <div class="col-md-5 animate fadeInLeft" id="plan-1" data-wow-delay="0.4s">
                <h3>Standard</h3>
                <p>Lorem ipsdolor sit amet, consectetur adipisc elit. Donec quis erat sed elit sceis Lorem ipsum dolor sit amet, </p>
                <div class="btn-part"> <a href="#." class="btn-large">select</a></div>
              </div>
              <div class="col-md-5 animate fadeInLeft" id="plan-2" data-wow-delay="0.4s">
                <h3>Premium</h3>
                <p>Lorem ipsdolor sit amet, consectetur adipisc elit. Donec quis erat sed elit sceis Lorem ipsum dolor sit amet, </p>
                <div class="btn-part"><a href="#." class="btn-large btn-large-1 ">select</a></div>
              </div>
            </div>
          </div>
        </div>

        <!-- Bottom BG Style -->
        <div class="cir-bottom-bg"></div>
    </section>
    <!-- d:[contact] SECTION -->
    <section class="tba" id="tba">
      <div class="cir-tri-bg"></div>
      <div class="container">

        <!-- Heading Block -->
        <div class="heading-block white">
          <h6 class=" animate fadeInRight" data-wow-delay="0.4s">What are you waiting for?</h6>
          <span class="huge-tittle">TBA</span></div>
        <div class="tba-body" id="contact-div"></div>
      </div>
      <div class="cir-bottom-bg"></div>
    </section>
  </div> <!-- End Content -->
  
<% else %>

  <div id="content">
    <!-- a:ABOUT SECTION-->
    <section class="hello" id="about">
      <!-- Diagonal Top -->
      <div class="cir-tri-bg"></div>
      <div class="container">
          <!-- Heading Block -->
          <div class="heading-block">
            <h6 class="animate fadeInRight" data-wow-delay="0.4s">What is Blocipedia?</h6>
            <span class="huge-tittle">about</span> </div>

          <div class="col-sm-5" data-wow-delay="0.5s">
            <%= image_tag "_img/icon-services-2.png", class:"hello-img animate fadeInLeft", alt:"blocipedia" %>

          <div class="col-sm-7">
            <h4>Simply put, Blocipedia is a place for Knowledge & Collaboration.</h4>
            <div class="test-info">
              <p>read, build, or collaborate on community-sourced content...</p>
              <a href="#." class="btn-flat">Get Started</a> </div>
          </div>
      </div>
      <!-- Bottom BG Style -->
      <div class="cir-bottom-bg"></div>
    </section>
    <!-- c:PLANS SECTION -->
    <section class="profile-main" id="plans" data-stellar-background-ratio="0.5">
        <!-- TOP bg Style -->
        <div class="cir-bottom-bg"></div>
        <div class="container">

          <!-- Heading Block -->
          <div class="heading-block">
            <h6 class="animate fadeInRight" data-wow-delay="0.4s">sign up today</h6>
            <span class="huge-tittle">plans</span> </div>

          <!-- Plan Tabs -->
          <div class="profile-inn plan-table">
            <div class="row">
              <div class="col-md-5 animate fadeInLeft" id="plan-1" data-wow-delay="0.4s">
                <h3>Standard</h3>
                <p>Lorem ipsdolor sit amet, consectetur adipisc elit. Donec quis erat sed elit sceis Lorem ipsum dolor sit amet, </p>
                <div class="btn-part"> <a href="#." class="btn-large">select</a></div>
              </div>
              <div class="col-md-5 animate fadeInLeft" id="plan-2" data-wow-delay="0.4s">
                <h3>Premium</h3>
                <p>Lorem ipsdolor sit amet, consectetur adipisc elit. Donec quis erat sed elit sceis Lorem ipsum dolor sit amet, </p>
                <div class="btn-part"><a href="#." class="btn-large btn-large-1 ">select</a></div>
              </div>
            </div>
          </div>
        </div>
        <!-- Bottom BG Style -->
        <div class="cir-bottom-bg"></div>
    </section>
  </div> <!-- End Content -->
<% end %>

app/views/welcome/old-index.html.erb
  <div class="hero">
      <div class="hero-feature row">
        <div class="col-sm">
          <!-- <%= image_tag "_old_img/mobile-tablet.png", class:"jumbotron-bgimg", alt:"blocipedia" %> -->
        </div>
        <div class="col-sm">
          <h1>Blocipedia</h1>
          <p class="lead">A place where you can build your own wikis and share them <br> publicly or privatly with other collaborators.</p>

          <%if user_signed_in?%>
          <%= link_to 'New Wiki', new_wiki_path, :class => 'login btn btn-lg'%>
          <% else %>
          <%= link_to 'Get Started', new_user_registration_path, :class => 'login btn btn-lg'%>
          <% end %>
        </div>

      </div>

  </div>

  <div class="hero" id="about-img">
    <div class="col about-feature">
        <p class="lead about-p">A place for sharing & creating awesome content</p>

    </div>
  </div>

  <div class="hero">
    <div class="call-to-action-feature row">
      <div class="col-sm">
        <p class="lead">Get started with your free account today!</p>
      </div>
      <div class="col-sm">

      </div>
    </div>
  </div>

app/views/welcome/plans.html.erb
<div class="content">
  <section class="bloc-plans" id="plans">
    <div class="container">
      <div class="row">
        <div class="col-lg heading-block">
          <h1 class="bloc-plans-heading huge-tittle">Select a Plan</h1>
        </div>
        <div class="col-sm-6 col-md-6">
          <div class="thumbnail">
            <%= image_tag "about-plan-placeholder1.png", class:"rounded-circle", alt:"Generic placeholder image" %>
            <div class="caption">
              <h2 class="plan">Standard</h2>
              <% if current_user.premium? %>
              <h6>Free</h6>
              <p>Sustainable Polaroid raw denim four loko vexillologist, hexagon viral whatever kitsch dreamcatcher umami art party. </p>
              <p><%= link_to "Free", downgrade_plan_path, :class =>"btn-sm"%></p>
              <% else %>
              <h6>Current Plan</h6>
              <p>Sustainable Polaroid raw denim four loko vexillologist, hexagon viral whatever kitsch dreamcatcher umami art party. </p>
              <p><a href="#" class="btn-sm disabled" role="button" aria-disabled="true">Free</a></p>
              <% end %>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-6">
          <div class="thumbnail">
            <%= image_tag "about-plan-placeholder2.png", class:"rounded-circle", alt:"Generic placeholder image" %>
            <div class="caption">
              <h2 class="plan">Premium</h2>
              <% if current_user.standard? %>
                <h6>Upgrade to unlock special features</h6>
                <p>DIY disrupt dreamcatcher, cornhole leggings pork belly meditation polaroid chia XOXO offal irony VHS shaman.</p>
                <p><%= link_to "$15.99", new_charge_path, :class =>"btn-sm"%></p>
              <% else %>
                <h6>Current Plan</h6>
                <p>DIY disrupt dreamcatcher, cornhole leggings pork belly meditation polaroid chia XOXO offal irony VHS shaman.</p>
                <p><a href="#" class="btn-sm disabled" role="button" aria-disabled="true">$15.00</a></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>

  </section>
</div>