config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :downgrade
  get 'downgrades', to: 'downgrades#downgrade_account', as: 'downgrade_plan'
  post 'downgrades', to: 'downgrades#downgrade_account', as: 'standard_plan'

  devise_for :users, controllers: {sessions: 'users/sessions'}
  resources :wikis
  # resources :users
  get '/plans', to: 'welcome#plans'
  get '/about', to: 'welcome#about'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :users, through: :collaborators
  after_initialize :set_private_default
  #add validations for wiki post (making sure there is a title and body).
  #add flash[:notice] to wiki's new view informing user of error.
  validates :title, presence: true
  validates :body, presence: true

  private
  def set_private_default
    self.private = false if self.private.nil?
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :require_sign_in, except: [:show]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    unless @wiki.private == false || @wiki.user == current_user|| current_user.admin? || current_user.role == "premium"
      flash[:alert]= "Sorry, but you need to be a premium member in order to access this post."
      redirect_to wikis_path
    end
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was published"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
     flash[:notice] = "Wiki was updated."
     redirect_to @wiki
    else
     flash.now[:alert] = "There was an error saving the wiki. Please try again."
     render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    flash.now[:alert] = 'Are you sure you want to delete this wiki?'

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was a problem deleting, try again."
      render :show
    end
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
    def wiki_params
      params.require(:wiki).permit(:title, :body, :id, :private)
    end

    def authorize_user
     @wiki = Wiki.find(params[:id])
     unless current_user == @wiki.user
       flash[:alert] = "You must be the author of the wiki to do that."
       redirect_to [@wikis]
     end
    end
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown(text)
    options = [:tables, :fenced_code_blocks, :autolink, :strikethrough, :underline, :highlight, :quote, :footnotes]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group private-checkbox">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> <p class="private-label">Private wiki</p>
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div id="content">
   <section class="wikis" id="wikis">

     <div class="container">
       <div class="col-sm-12 heading-block-view wiki-show-view-heading">
         <div class="col-md-8">
           <h1 class="huge-tittle animate fadeInRight">Edit</h1>
         </div>
         <div class="col-md-4">
           <%= link_to "Back to Wikis", wikis_path, class: 'btn-flat' %>
         </div>
       </div>

       <hr class="featurette-divider">

       <div class="flash-container">
         <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
         <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
         <% end %>
       </div>

       <div class="row">
         <div class="col-md-8 wiki-list">
           <div class="media media-body">
             <%= form_for @wiki do |f| %>
             <%= f.label :title, class: 'media-heading'%>
             <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
             <br />
             <%= f.label :body, class: 'media-heading' %>
             <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
             <div class="form-group">
               <%= render partial: "form", locals: {f: f}%>
               <br>
               <%= f.submit "Save", class: 'btn-sm' %>
             </div>
          <% end %>
           </div>
         </div>

         <div class="col-md-4 wiki-btn-col">
           <div class="media">
             <div class="media-body">
               <!-- need to fix to check if current_user is author of wiki. if so show the following: -->
                 <% if current_user == @wiki.user %>
                   <%= link_to "Delete", @wiki, method: :delete, class: 'btn-sm', data: { confirm: 'Are you sure you want to delete this wiki?' }%>
                 <% end %>

               <p class="small">
                <strong>created by: </strong>
                 <%= @wiki.user.email%>
                <strong>collaborators: </strong>
                <% @wiki.user do |u| %>
                  <%= u.user.email %>
                <% end %>
               </p>
             </div>
           </div>
         </div>
       </div>

     </div>
   </section>
 </div>

app/views/wikis/index.html.erb
<div id="content">
  <section class="wikis" id="wikis">
    <div class="container">
      <div class="col-sm-12">
        <div class="heading-block-view">
          <h1 class="huge-tittle animate fadeInRight">Popular Wikis</h1>
        </div>
        <hr class="featurette-divider">
        <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
        <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
        <% end %>
      </div>

      <div class="row">
        <div class="col-md-8 wiki-list">
          <% @wikis.each do |wiki| %>
            <div class="media">
              <div class="media-body">
                <h4 class="media-heading">
                  <%= link_to wiki.title, wiki %>
                </h4>
                <small>
                  submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.email %>
                </small>
              </div>
            </div>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <div class="col-md-4 wiki-btn-col">
            <%=link_to "New Wiki", new_wiki_path, class: 'btn-sm'%>
          </div>
        <% end %>
      </div>

    </div>
  </section>
</div>

app/views/wikis/new.html.erb
<div class="content">
  <section class="new-wiki">
    <div class="new-wiki-title-block">
      <h1 class="new-wiki-title animate fadeInRight">New Wiki</h1>
      <p class="lead"> Do you want to add collaborators?
      </p>
    </div>

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>

    <div class="row">
      <div class="col-md-8">
        <%= form_for @wiki do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
        <%= render partial: "form", locals: {f: f}%>
        <div class="form-group">
          <br>
          <%= f.submit "Save", class: 'btn-sm' %>
        </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/wikis/show.html.erb
<div id="content">
  <section class="wikis" id="wikis">
    <div class="container">
      <div class="col-sm-12 heading-block-view wiki-show-view-heading">
        <div class="col-md-8">
          <!-- <h1 class="animate fadeInRight">Create</h1> -->
        </div>
        <div class="col-md-4">
          <%= link_to "Back to Wikis", wikis_path, class: 'btn-flat' %>
        </div>
      </div>
      <!-- <hr class="featurette-divider"> -->

      <div class="row">
        <div class="col-md-8 wiki-list">
          <div class="media">
            <div class="flash-container">
              <% if flash[:notice] %>
              <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:notice] %>
              </div>
              <% elsif flash[:alert] %>
              <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:alert] %>
              </div>
              <% end %>
            </div>
            <h4><%= @wiki.title %></h4>
              <div class="media-body">
                <p class="lead"><%= markdown(@wiki.body)%></p>
                <small>
                  submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
                </small>
              </div>
            </div>
        </div>

        <div class="col-md-4 wiki-btn-col">
          <div class="media">
            <div class="media-body">
            <!-- need to fix to check if current_user is author of wiki. if so show the following: -->
            <% if current_user %>
              <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn-sm'%>
              <%= link_to "Delete", @wiki, method: :delete, class: 'btn-sm', data: { confirm: 'Are you sure you want to delete this wiki?' }%>
            <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>
</div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>