config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  resources :downgrade
  get 'downgrades', to: 'downgrades#downgrade_account', as: 'downgrade_plan'
  post 'downgrades', to: 'downgrades#downgrade_account', as: 'standard_plan'

  devise_for :users, controllers: {sessions: 'users/sessions'}
  resources :wikis
  # resources :users
  get '/plans', to: 'welcome#plans'
  get '/about', to: 'welcome#about'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :amount_to_be_charged
  before_action :set_description
  before_action :authenticate_user!

  def new
  end

  def create
    customer = Stripe::Customer.create(
                  email: params[:stripeEmail],
                  source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
                  customer: customer.id,
                  amount: @amount,
                  currency: 'usd',
                  description: @description
    )

    current_user.update_attribute(:role, 1)

    flash[:notice] = "Payment Approved."

    redirect_to thanks_path
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def thanks
  end

  private

      def set_description
        @description = "Premium Membership"
      end

      def amount_to_be_charged
        @amount = 1500
      end

end

app/helpers/charges_helper.rb
module ChargesHelper
  def pretty_amount(amount_in_cents)
    number_to_currency(amount_in_cents / 100)
  end
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<div id="content">
  <section class="upgrade">
    <div class="container">
      <div class="col-sm-12">
        <div class="heading-block">
          <div class="col-sm-12">
            <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
            <% end %>
          </div>
          <h3 class="upgrade-title animate fadeInRight">Upgrade to Premium</h3>
          <dv class="col-sm-8">
            <h6 class="upgrade-subtitle animate fadeInRight">to unlock additional features</h6>
            <%= form_tag charges_path do %>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="<%= @description %>"
            data-amount="<%= @amount %>"
            data-email="<%= current_user.email %>"
            data-bitcoin="true"
            data-locale="auto"></script>
            <% end %>
          </dv>
          <%= image_tag "_img/icon-services-2.png", class:"upgrade-img animate fadeInLeft col-sm-4", alt:"blocipedia" %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/charges/thanks.html.erb
<div id="content">
  <section class="thank-you">
    <div class="container">
      <div class="col-sm-6">
        <div class="heading-block">
          <h1 class="huge-tittle animate fadeInRight">Thank You!</h1>
          <h6 class="animate fadeInRight">You are now a Premium Member</h6>
          <%= image_tag "_img/icon-services-2.png", class:"about-img animate fadeInLeft", alt:"blocipedia" %>
        </div>
      </div>

        <div class="col-sm-6">
          <div class="about-lead">
            <p class="lead">read, build, or collaborate on community-sourced content...
            <br>
            <br>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <div>
              <%=link_to "create", new_wiki_path, class: 'btn-sm'%>
            </div>
          </div>
        </div>
    </div>
  </section>
</div>